config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/pictures/instagram', to: 'pictures#instagram'

  post '/pictures/instagram', to: 'pictures#instagram_location'

  resources :pictures

  resources :videos

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :url, :presence => {:message => 'URL cannot be blank'}
  validates :description, :presence => {:message => 'Description cannot be blank'}
  validates :url, format: {
    with: /(https?:\/\/)?(www.)?((\w*)\.)+(\w){2,6}([\/\w\-\+])*(?i)(\.ani|\.bmp|\.cal|\.fax|\.gif|\.img|\.jbg|\.jpe|\.jpeg|\.jpg|\.mac|\.pbm|\.pcd|\.pcx|\.pct|\.pgm|\.png|\.ppm|\.psd|\.ras|\.tga|\.tiff|\.wmf)/,
    message: "URL must be valid"}
  validates :rating, :numericality => {:only_integer => true, :message => 'Rating must be a number between 0 and 5'}
  validates :rating, :inclusion => {:in => (0..5), :message => 'Rating must be a number between 0 and 5'}
end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :url, presence: true
  validates :url, format: {
    with: /(https?:\/\/youtu.be\/)|(https?:\/\/www.youtube.com\/watch\?v=)/,
    message: "must come from Youtube"}
  validates :description, presence: true
  validates :rating, :numericality => {:only_integer => true, :message => 'Rating must be a number between 0 and 5'}
  validates :rating, :inclusion => {:in => (0..5), :message => 'Rating must be a number between 0 and 5'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
require "instagram"

class PicturesController < ApplicationController
  Instagram.configure do |config|
    config.client_id = ENV["INSTAGRAM_CLIENT_ID"]
    config.client_secret = ENV["INSTAGRAM_CLIENT_SECRET"]
  end

  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    picture = Picture.new(allowed_parameters)
    if picture.save
      redirect_to "/pictures/#{picture.id}", notice: "Picture successfully created"
    else
      @picture = picture
      render :new
    end
  end

  def show
    @picture = Picture.find(params[:id])
  end

  def edit
    @picture = Picture.find(params[:id])
    render :edit
  end

  def update
    picture = Picture.find(params[:id])
    picture.update_attributes(allowed_parameters)
    if picture.save
      redirect_to "/pictures/#{picture.id}", notice: "Picture successfully edited"
    else
      @picture = picture
      render :edit
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to pictures_path
  end

  def instagram
    client = Instagram.client
    @latitude = (params[:latitude] || '40.0176335')
    @longitude = (params[:longitude] || '-105.2819911')
    @media_items = client.media_search(@latitude, @longitude)
  end

  def instagram_location
    redirect_to "/pictures/instagram?latitude=#{params[:latitude]}&longitude=#{params[:longitude]}"
  end

  private

  def allowed_parameters
    params.require(:picture).permit(:url, :description, :rating)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new
    @video.url = params[:video][:url]
    @video.description = params[:video][:description]
    @video.rating = params[:video][:rating]
    if @video.save
      redirect_to "/videos/#{@video.id}", notice: "Video successfully created"
    else
      render :new
    end
  end

  def show
    @video = Video.find(params[:id])
    @youtube_id = @video.url.split(%r{(https?:\/\/youtu.be\/)|(https?:\/\/www.youtube.com\/watch\?v=)}).last
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])
    @video.url = params[:video][:url]
    @video.description = params[:video][:description]
    @video.rating = params[:video][:rating]
    if @video.save
      redirect_to "/videos/#{@video.id}"
    else
      render :new
    end
  end

  def destroy
    Video.destroy(params[:id])
    redirect_to '/videos', notice: "Video successfully deleted"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FloralViolet</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div id="nav-container">
    <div id="left-nav-links">
      <a href="/">Media Manager</a>
    </div>
    <div id="right-nav-links">
      <p><a href="/pictures">All Pictures</a> |
        <a href="/videos">All Videos</a></p>
    </div>
    <div class="resetColumnSet"></div>
  </div>
</header>
<div id="content_container"><%= yield %></div>
<footer>
  <div id="footer_container">Not Copyrighted At All</div>
</footer>
</body>
</html>

app/views/pictures/edit.html.erb
<div id="picture_form">
  <h1>Edit a picture</h1>

  <%= form_for @picture, url: {action: 'update'}, id: 'picture-form' do |f| %>
    <% if @picture.errors.any? %>
      <div class="errors">
        <% @picture.errors.each do |_, msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    <table>
      <tr>
        <td><%= f.label :url_of_picture %></td>
        <td><%= f.text_field :url, :id => 'url' %></td>
      </tr>
      <br/>
      <tr>
        <td><%= f.label :short_description %></td>
        <td><%= f.text_area :description, :id => 'description' %></td>
      </tr>
      <br/>
      <tr>
        <td><%= f.label :rating %></td>
        <td><%= f.text_field :rating, :id => 'rating' %></td>
      </tr>
      <tr>
        <td></td>
        <td> <%= f.submit 'Update Picture', :id => 'picture-button' %> </td>
      </tr>
    </table>
    <br/>


  <% end %>
</div>

app/views/pictures/index.html.erb
<h1>Pictures</h1>
<%= link_to('New Picture', action: 'new') %><br />
<%= link_to("View Instagram Photos", action: 'instagram') %>
<div id="picture-list">
  <% @pictures.each do |picture| %>
    <a href="/pictures/<%= picture.id %>" id="show_<%= picture.id %>"><img class="thumbnail" src="<%= picture.url %>"/></a>
  <% end %>
</div>

app/views/pictures/instagram.html.erb
<h1>Instagram Location Stream</h1>
<div id="location_form">
<%= form_tag("/pictures/instagram", method: "post") do %>
  <%= text_field_tag(:latitude, @latitude, :placeholder => 'latitude') %>
  <%= text_field_tag(:longitude, @longitude, :placeholder => 'longitude') %>
  <%= submit_tag("Update Location") %>
<% end %>
</div>

<% counter = 0 %>
<% @media_items.each do |media_item| %>
  <div id="instagram" class="one_half">
    <div id="instagram_image">
      <img src="<%= media_item.images.thumbnail.url %>">
    </div>
    <div id="instagram_info">
      <p>
        <% if media_item.caption %>
          <% if media_item.caption.text.length > 50 %>
            <%= (media_item.caption.text)[0..50] + "..." %>
          <% else %>
            <%= media_item.caption.text %>
          <% end %>
        <% end %><br/>
        <span class='bold'><%= pluralize(media_item[:likes][:count], 'like') %></span>
      </p>
      <a href='<%= media_item.link %>'>View</a><br/>
      <span class="bold"><%= media_item.user.username %></span><br/>
      <%= link_to "Open in App", "instagram://media?id=#{media_item.id}", class: 'app-link' %>
    </div>
  </div>
  <% counter += 1 %>
  <% if counter.even? %>
    <div class="resetColumnSet"></div>
  <% end %>
<% end %>
<div class="resetColumnSet"></div>

<script type="text/javascript">
  $(function () {
    $(".app-link").click(function () {
      var timeout;

      function try_to_open_app() {
        timeout = setTimeout(function () {
          window.location='http://itunes.com/';
        }, 300);
      }

      try_to_open_app();
    });
  })
</script>

app/views/pictures/new.html.erb
<div id="picture_form">
  <h1>Add a picture</h1>

  <%= form_for @picture, url: {action: 'create'}, id: 'picture-form' do |f| %>
    <% if @picture.errors.any? %>
      <div class="errors">
        <% @picture.errors.each do |_, msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    <% end %>
    <table>
      <tr>
        <td><%= f.label :url_of_picture %></td>
        <td><%= f.text_field :url, :id => 'url' %></td>
      </tr>
      <br/>
      <tr>
        <td><%= f.label :short_description %></td>
        <td><%= f.text_area :description, :id => 'description' %></td>
      </tr>
      <br/>
      <tr>
        <td><%= f.label :rating %></td>
        <td><%= f.text_field :rating, :id => 'rating' %></td>
      </tr>
      <tr>
        <td></td>
        <td> <%= f.submit 'Create Picture', :id => 'picture-button' %></td>
      </tr>
    </table>
   

  <% end %>
</div>

app/views/pictures/show.html.erb
<div class="full_column" id="notice">
  <% flash.each do |_, msg| -%>
    <%= msg %>
  <% end -%>
  <div class="resetColumnSet"></div>
</div>
<!--end full_column-->
<div class="one_third" id="left_side">
  <img src="<%= @picture.url %>" class="thumbnail">

  <p>Rating: <%= @picture.rating %> out of 5</p>
</div>
<div class="one_third" id="right_side">
  <p id="url">
    <a href="<%= @picture.url %>"><%= @picture.url %></a> &nbsp; <a href="/pictures/<%= @picture.id %>/edit">(Edit)</a>
  </p>

  <p><%= simple_format(@picture.description) %></p>
</div>
<div class="resetColumnSet"></div>
<div class="one_third" id="left_side">&nbsp;</div>
<div class="one_third" id="right_side">
  <%= button_to('Delete Picture', picture_path(@picture), method: :delete, :id => "delete_button") %>
</div>
<div class="resetColumnSet"></div>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>

<%= form_for @video do |f| %>

  <% if @video.errors.present? %>
    <div class="errors">
      <% @video.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
    <br>
  <% end %>

  <table id="video_form">
    <tr>
      <td>
        <%= f.label :url, text = 'URL of Video' %>
      </td>
      <td class="wide">
        <%= f.text_field :url %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :description, text = 'Short Description' %>
      </td>
      <td class="wide">
        <%= f.text_area :description %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :rating %>
      </td>
      <td>
        <%= f.text_field :rating %>
      </td>
    </tr>

    <tr>
      <td></td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>

app/views/videos/index.html.erb
<h1>Videos</h1>

<div class="full_column" id="notice">
  <% flash.each do |_, msg| -%>
    <h3><%= msg %></h3>
  <% end -%>
  <div class="resetColumnSet"></div>
</div>

<a href="/videos/new">New Video</a>

<% @videos.each do |video| %>
  <p><a href='/videos/<%= video.id %>'><%= video.url %></a></p>
<% end %>

app/views/videos/new.html.erb
<h1>Add a Video</h1>

<%= form_for @video do |f| %>

  <% if @video.errors.present? %>
    <div class="errors">
      <% @video.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
    <br>
  <% end %>
  <table id="video_form">
    <tr>
      <td>
        <%= f.label :url, text = 'URL of Video' %>
      </td>
      <td class="wide">
        <%= f.text_field :url %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :description, text = 'Short Description' %>
      </td>
      <td class="wide">
        <%= f.text_area :description %>
      </td>
    </tr>

    <tr>
      <td>
        <%= f.label :rating %>
      </td>
      <td>
        <%= f.text_field :rating %>
      </td>
    </tr>

    <tr>
      <td></td>
      <td>
        <%= f.submit %>
      </td>
    </tr>
  </table>
<% end %>

app/views/videos/show.html.erb
<div class="full_column" id="notice">
  <% flash.each do |_, msg| -%>
    <h3><%= msg %></h3>
  <% end -%>
  <div class="resetColumnSet"></div>
</div>
<div class="one_half">
  <iframe width="420" height="315" src="//www.youtube.com/embed/<%= @youtube_id %>" frameborder="0" allowfullscreen></iframe>
  <p>Rating: <%= @video.rating %> out of 5</p>
</div>


<div class="one_half">
  <p id="url">
    <a href=<%= @video.url %>><%= @video.url %></a> &nbsp; <a href="/videos/<%= @video.id %>/edit">(Edit)</a>
  </p>

  <p><%= simple_format(@video.description) %></p>
  <% 5.times do %>
    <br>
  <% end %>
  <%= button_to "Delete Video", video_path(@video), method: :delete, data: {confirm: "Are you sure?"}, :id => "delete_button" %>
</div>

app/views/welcome/index.html.erb
<div class="full_column">
  <br><br>
  <h3>Welcome to the media manager, where you can, well... manage some media.</h3>
  <br><br>
</div>

<div class="one_half" id="pictures_home">
  <h1>Pictures!</h1>

  <p>&nbsp;<a href="/pictures">View All</a></p>

  <p>&nbsp;<a href="/pictures/new">Add New</a></p>
</div>

<div class="one_half" id="videos_home">
  <h1>Videos!</h1>

  <p>&nbsp;<a href="/videos">View All</a></p>

  <p>&nbsp;<a href="/videos/new">Add New</a></p>
</div>